// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelGuide.Data;

#nullable disable

namespace TravelGuide.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TravelGuide.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            History = "Кремль — сердце российской государственности, крепость XII века. Красная площадь рядом с ним веками была местом народных собраний. Ансамбль включён в список Всемирного наследия ЮНЕСКО.",
                            Name = "Московский Кремль и Красная площадь",
                            PhotoUrl = "/images/attractions/kremlin.jpg",
                            TicketPrice = "от 500 руб.",
                            WorkingHours = "09:00–18:00, кроме четверга"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            History = "Крупнейшее в мире собрание русского искусства. Основана купцом Павлом Третьяковым в 1856 году. Коллекция — более 180 000 произведений.",
                            Name = "Третьяковская галерея",
                            PhotoUrl = "/images/attractions/tretyakov.jpg",
                            TicketPrice = "от 600 руб.",
                            WorkingHours = "10:00–18:00, пт–сб до 21:00, пн — выходной"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            History = "Один из крупнейших оперных и балетных театров мира. История с 1776 года. Нынешнее здание в стиле ампир открылось в 1856 году.",
                            Name = "Большой театр",
                            PhotoUrl = "/images/attractions/bolshoi.jpg",
                            TicketPrice = "от 1000 руб.",
                            WorkingHours = "По расписанию спектаклей"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            History = "Один из крупнейших художественных музеев мира. Основан в 1764 году Екатериной II. Коллекция — более 3 миллионов экспонатов.",
                            Name = "Государственный Эрмитаж",
                            PhotoUrl = "/images/attractions/hermitage.jpg",
                            TicketPrice = "от 500 руб.",
                            WorkingHours = "10:30–18:00, вт и чт до 21:00, пн — выходной"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            History = "Дворцово-парковый ансамбль на берегу Финского залива, основан Петром I. Более 150 фонтанов и 4 каскада. Включён в список Всемирного наследия ЮНЕСКО.",
                            Name = "Петергоф",
                            PhotoUrl = "/images/attractions/peterhof.jpg",
                            TicketPrice = "от 450 руб.",
                            WorkingHours = "Парки: 09:00–21:00, пн — выходной"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            History = "Крупнейший православный храм Санкт-Петербурга. Строился 40 лет (1818–1858). Высота купола — 101,5 м. С колоннады открывается панорама города.",
                            Name = "Исаакиевский собор",
                            PhotoUrl = "/images/attractions/isaac.jpg",
                            TicketPrice = "от 350 руб.",
                            WorkingHours = "10:30–18:00, чт — выходной"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            History = "Единственный в мире сохранившийся татарский кремль, история с X–XI веков. Внесён в список Всемирного наследия ЮНЕСКО.",
                            Name = "Казанский Кремль",
                            PhotoUrl = "/images/attractions/kazan_kremlin.jpg",
                            TicketPrice = "Территория бесплатно; музеи от 150 руб.",
                            WorkingHours = "08:00–20:00 ежедневно"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            History = "Главная мечеть Татарстана, возведена в 1996–2005 годах. Вмещает 6000 верующих. Четыре 57-метровых минарета стали символом Казани.",
                            Name = "Мечеть Кул-Шариф",
                            PhotoUrl = "/images/attractions/kul_sharif.jpg",
                            TicketPrice = "Бесплатно",
                            WorkingHours = "Ежедневно"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 4,
                            History = "Построен к Зимним Олимпийским играм 2014 года. Здесь расположены главные олимпийские арены. Принял матчи ЧМ по футболу 2018 года.",
                            Name = "Олимпийский парк",
                            PhotoUrl = "/images/attractions/olympic.jpg",
                            TicketPrice = "Вход на территорию бесплатно",
                            WorkingHours = "09:00–21:00 ежедневно"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 4,
                            History = "Горнолыжный курорт мирового уровня в Красной Поляне, высота 560–2320 м. Здесь проходили соревнования Зимней Олимпиады 2014 года. Открыт круглогодично.",
                            Name = "Горнолыжный курорт Роза Хутор",
                            PhotoUrl = "/images/attractions/rosa.jpg",
                            TicketPrice = "Подъёмники от 800 руб./день",
                            WorkingHours = "09:00–17:00"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 5,
                            History = "Построен в 2000–2003 годах на месте дома, где в 1918 году была расстреляна семья Николая II. Крупнейший православный собор Екатеринбурга.",
                            Name = "Храм-на-Крови",
                            PhotoUrl = "/images/attractions/khram.jpg",
                            TicketPrice = "Бесплатно",
                            WorkingHours = "07:00–21:00 ежедневно"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 5,
                            History = "Президентский центр первого президента России, открылся в 2015 году. Рассказывает об эпохе 1990-х. Включает арт-галерею, медиатеку и кинотеатр.",
                            Name = "Ельцин-центр",
                            PhotoUrl = "/images/attractions/yeltsin.jpg",
                            TicketPrice = "от 200 руб.",
                            WorkingHours = "10:00–21:00, пн — выходной"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 6,
                            History = "Научный центр России, основан в 1957 году. Здесь расположены десятки институтов Сибирского отделения РАН и НГУ. Один из крупнейших научных центров мира.",
                            Name = "Новосибирский Академгородок",
                            PhotoUrl = "/images/attractions/akadem.jpg",
                            TicketPrice = "Бесплатно",
                            WorkingHours = "Открытая территория"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 6,
                            History = "Крупнейший оперный театр России и Азии. Построен в 1945 году. Диаметр купола — 60 м. В репертуаре — шедевры мировой оперы и балета.",
                            Name = "Новосибирский оперный театр",
                            PhotoUrl = "/images/attractions/nsk_opera.jpg",
                            TicketPrice = "от 300 руб.",
                            WorkingHours = "По расписанию спектаклей"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 7,
                            History = "Каменная крепость XVI века на высоком берегу Волги. Никогда не был взят врагами. Внутри — административный центр города и Архангельский собор.",
                            Name = "Нижегородский Кремль",
                            PhotoUrl = "/images/attractions/nn_kremlin.jpg",
                            TicketPrice = "Территория бесплатно; музеи от 200 руб.",
                            WorkingHours = "08:00–20:00 ежедневно"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 7,
                            History = "Знаменитая лестница, построенная в 1949 году в честь лётчика Чкалова. Соединяет Верхневолжскую и Нижневолжскую набережные. Насчитывает 560 ступеней.",
                            Name = "Чкаловская лестница",
                            PhotoUrl = "/images/attractions/chkalov.jpg",
                            TicketPrice = "Бесплатно",
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 8,
                            History = "Один из крупнейших вантовых мостов в мире, открыт в 2012 году к саммиту АТЭС. Соединяет Владивосток с островом Русский. Длина центрального пролёта — 1104 м.",
                            Name = "Русский мост",
                            PhotoUrl = "/images/attractions/russkiy.jpg",
                            TicketPrice = "Бесплатно",
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 8,
                            History = "Центральная набережная Владивостока с видом на Амурский залив. Место прогулок горожан и туристов. Рядом расположены Приморский океанариум и причалы.",
                            Name = "Набережная Цесаревича",
                            PhotoUrl = "/images/attractions/vlad_nab.jpg",
                            TicketPrice = "Бесплатно",
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 9,
                            History = "Готический собор XIV века, памятник средневековой прусской архитектуры. Здесь похоронен философ Иммануил Кант. Включён в список объектов ЮНЕСКО.",
                            Name = "Кафедральный собор на острове Канта",
                            PhotoUrl = "/images/attractions/cathedral_kant.jpg",
                            TicketPrice = "от 200 руб.",
                            WorkingHours = "10:00–18:00"
                        },
                        new
                        {
                            Id = 20,
                            CityId = 9,
                            History = "Единственный в мире музей янтаря. Коллекция насчитывает более 14 000 экспонатов. Расположен в Башне «Дона» — памятнике прусской военной архитектуры.",
                            Name = "Музей Янтаря",
                            PhotoUrl = "/images/attractions/amber.jpg",
                            TicketPrice = "от 300 руб.",
                            WorkingHours = "10:00–18:00, пн — выходной"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 10,
                            History = "Крупнейшая конная статуя в России (высота 9,8 м). Установлена в 1967 году на высоком берегу реки Белой. Посвящена национальному герою башкирского народа.",
                            Name = "Памятник Салавату Юлаеву",
                            PhotoUrl = "/images/attractions/salavat.jpg",
                            TicketPrice = "Бесплатно",
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 22,
                            CityId = 10,
                            History = "Один из старейших музеев региона, основан в 1864 году. Хранит более 240 000 экспонатов по истории, природе и культуре Башкортостана.",
                            Name = "Национальный музей Башкортостана",
                            PhotoUrl = "/images/attractions/ufa_museum.jpg",
                            TicketPrice = "от 150 руб.",
                            WorkingHours = "10:00–18:00, пн — выходной"
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoatOfArmsUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Population")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoatOfArmsUrl = "/images/coats/moscow.png",
                            History = "Москва основана в 1147 году князем Юрием Долгоруким. Веками служила столицей Великого Московского княжества, Российского царства и Российской Федерации. В 1812 году была захвачена Наполеоном, но восстановлена. В советское время появились знаменитые сталинские высотки. Сегодня — крупнейший финансовый и культурный центр России.",
                            Name = "Москва",
                            PhotoUrl = "/images/cities/moscow.jpg",
                            Population = "13 010 112",
                            Region = "Центральный федеральный округ",
                            ShortDescription = "Столица России, крупнейший город страны."
                        },
                        new
                        {
                            Id = 2,
                            CoatOfArmsUrl = "/images/coats/spb.png",
                            History = "Основан Петром I в 1703 году. Служил столицей Российской империи до 1918 года. Во Второй мировой войне выдержал 872-дневную блокаду. Один из красивейших городов мира с уникальной барочной архитектурой.",
                            Name = "Санкт-Петербург",
                            PhotoUrl = "/images/cities/spb.jpg",
                            Population = "5 600 044",
                            Region = "Северо-Западный федеральный округ",
                            ShortDescription = "Северная столица России, город каналов и белых ночей."
                        },
                        new
                        {
                            Id = 3,
                            CoatOfArmsUrl = "/images/coats/kazan.png",
                            History = "Основана в XIII веке, стала столицей Казанского ханства. В 1552 году взята Иваном Грозным. Уникальное место, где переплетаются татарская и русская культуры. Принимала Универсиаду 2013 и ЧМ по футболу 2018.",
                            Name = "Казань",
                            PhotoUrl = "/images/cities/kazan.jpg",
                            Population = "1 316 162",
                            Region = "Приволжский федеральный округ",
                            ShortDescription = "Столица Татарстана, место встречи двух культур."
                        },
                        new
                        {
                            Id = 4,
                            CoatOfArmsUrl = "/images/coats/sochi.png",
                            History = "Самый длинный город России — 145 км вдоль Черного моря. В советское время стал главной всесоюзной здравницей. Принял Зимние Олимпийские игры 2014 года. Уникальный климат позволяет совмещать море с горнолыжным отдыхом.",
                            Name = "Сочи",
                            PhotoUrl = "/images/cities/sochi.jpg",
                            Population = "502 537",
                            Region = "Краснодарский край",
                            ShortDescription = "Главный курорт России на черноморском побережье."
                        },
                        new
                        {
                            Id = 5,
                            CoatOfArmsUrl = "/images/coats/ekb.png",
                            History = "Основан в 1723 году Петром I. Сыграл ключевую роль в индустриализации страны. В 1918 году здесь была расстреляна семья Романовых. В советское время как Свердловск стал крупнейшим промышленным центром. Сегодня — динамично развивающийся мегаполис.",
                            Name = "Екатеринбург",
                            PhotoUrl = "/images/cities/ekb.jpg",
                            Population = "1 537 590",
                            Region = "Уральский федеральный округ",
                            ShortDescription = "Столица Урала, четвёртый по величине город России."
                        },
                        new
                        {
                            Id = 6,
                            CoatOfArmsUrl = "/images/coats/novosibirsk.png",
                            History = "Основан в 1893 году как поселение при строительстве Транссибирской магистрали. Быстро вырос и получил статус города в 1903 году. В советское время стал крупнейшим промышленным центром Сибири. Здесь расположен знаменитый Академгородок — центр науки России.",
                            Name = "Новосибирск",
                            PhotoUrl = "/images/cities/novosibirsk.jpg",
                            Population = "1 633 595",
                            Region = "Сибирский федеральный округ",
                            ShortDescription = "Крупнейший город Сибири, научный и культурный центр."
                        },
                        new
                        {
                            Id = 7,
                            CoatOfArmsUrl = "/images/coats/nnov.png",
                            History = "Основан в 1221 году как форпост на слиянии Оки и Волги. В XVII веке стал крупнейшим торговым центром — здесь проходила знаменитая Нижегородская ярмарка. В советское время как Горький был закрытым промышленным городом. Сегодня — один из культурных центров Поволжья.",
                            Name = "Нижний Новгород",
                            PhotoUrl = "/images/cities/nnov.jpg",
                            Population = "1 228 199",
                            Region = "Приволжский федеральный округ",
                            ShortDescription = "Пятый город России, слияние Оки и Волги."
                        },
                        new
                        {
                            Id = 8,
                            CoatOfArmsUrl = "/images/coats/vladivostok.png",
                            History = "Основан в 1860 году как военный пост. Название «Владей Востоком» отражает его стратегическое значение. Конечная точка Транссибирской магистрали. Долгое время был закрытым городом. Сегодня — крупнейший порт Дальнего Востока.",
                            Name = "Владивосток",
                            PhotoUrl = "/images/cities/vladivostok.jpg",
                            Population = "603 519",
                            Region = "Дальневосточный федеральный округ",
                            ShortDescription = "Ворота России в Азиатско-Тихоокеанский регион."
                        },
                        new
                        {
                            Id = 9,
                            CoatOfArmsUrl = "/images/coats/kaliningrad.png",
                            History = "Основан Тевтонским орденом в 1255 году как Кёнигсберг. Веками был центром Пруссии, родиной философа Иммануила Канта. После Второй мировой войны отошёл к СССР и переименован в Калининград. Уникальный российский эксклав на Балтийском море с богатым европейским наследием.",
                            Name = "Калининград",
                            PhotoUrl = "/images/cities/kaliningrad.jpg",
                            Population = "489 359",
                            Region = "Калининградская область",
                            ShortDescription = "Самый западный город России, бывший Кёнигсберг."
                        },
                        new
                        {
                            Id = 10,
                            CoatOfArmsUrl = "/images/coats/ufa.png",
                            History = "Основана в 1574 году как русская крепость на башкирских землях. Расположена на высоком берегу при слиянии рек Белой и Уфы. В XIX–XX веках стала крупным нефтеперерабатывающим центром. Сегодня Уфа — многонациональный город с богатым культурным наследием башкирского, татарского и русского народов.",
                            Name = "Уфа",
                            PhotoUrl = "/images/cities/ufa.jpg",
                            Population = "1 144 809",
                            Region = "Республика Башкортостан",
                            ShortDescription = "Столица Башкортостана, город на слиянии рек."
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Attraction", b =>
                {
                    b.HasOne("TravelGuide.Models.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelGuide.Models.City", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
